

#--------------------------------------------------------
# STEP 1: Allocation
#--------------------------------------------------------

#TAKE THE BEST APPRAOCH AND LET IT RUN. SAVE THE BEST STRATEGY OF EACH RUN AND SAVE THE CURRENT FOUND ONE
# THEN WE HAVE ONE PLOT SHOWING THE MONOTON GROWING TARGET FUNCTION AND ANOTHER ONE SHOWING NEW RESULTS OF NEW SPANNING TREES.
#THIS IS DONE FOR DIFFERENT GENERATION SIZES. THE BEST GENERATION SIZE IS THEN COMPARED TO A COMPLETE RANDOM SPANNING TREE GENERATION